name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rust-src
          target: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          cache: 'npm'

      - name: NPM install
        run: npm ci

      - name: Make build script executable
        run: chmod +x ./build.sh

      # This handles the rest.
      # If this fails with "permission denied", run: `git update-index --chmod=+x build.sh` locally and push
      - name: Run build script
        run: ./build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: pages
          commit-message: Deploying to GitHub Pages from ${{ github.event.head_commit.url }}
          clean: true
          git-config-email: github-actions[bot]@users.noreply.github.com