name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Trunk build
        run: trunk build --release

#      - name: Run tests
#        run: cargo test

      # Because this is an SPA, navigating to a route without first going "through the base (the client)" will result in a 404.
      # In a nutshell, without this, going to "example.com/contact" would result in a 404.
      # So if we configure 404 to go to the client, it will work as expected.
      # More info here: https://yew.rs/docs/more/deployment#server-configuration
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages
          FOLDER: dist